CREATE TYPE PR_STATUS AS ENUM ('open', 'merged');


CREATE TABLE IF NOT EXISTS "user" (
    _id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS team (
    _id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    team_id TEXT NOT NULL,
    team_name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS team_member (
    _id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    team_id INT NOT NULL REFERENCES team(_id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES "user"(_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pull_request (
    _id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    pr_id TEXT UNIQUE NOT NULL,
    req_title TEXT NOT NULL,
    author_id INT NOT NULL REFERENCES team_member(_id) ON DELETE CASCADE,
    status PR_STATUS NOT NULL
);

CREATE TABLE IF NOT EXISTS reviewer (
    _id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    req_id INT NOT NULL REFERENCES pull_request(_id) ON DELETE CASCADE,
    user_id INT NOT NULL REFERENCES team_member(_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ,
    merged_at TIMESTAMPTZ
);